name: Valparaíso

concurrency:
  group: valparaisodegoias
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - workflows_config

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: "production"
      NEXT_TELEMETRY_DISABLED: "1"

      SKIP_PREFLIGHT_CHECK: "true"
      CI: "false"
      GENERATE_SOURCEMAP: "false"
      NEXT_PUBLIC_API_URL: "http://209.126.1.173"
      NEXT_PUBLIC_SITE_URL: "https://materiavalparaisodegoias.virtualis.ia.br"
      NEXT_PUBLIC_BUILD_MODE: "static"
      NEXT_PUBLIC_ENABLE_AI: "true"
      NEXT_PUBLIC_ENABLE_TRANSCRIPTION: "true"
      NEXT_PUBLIC_ENABLE_ADMIN: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalando dependências
        run: npm ci

      - name: Build (Next)
        run: npm run build

      - name: Export static (Next -> /out)
        run: npm run export

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vercel/output/static --project-name=materiavalparaisodegoias --branch main
